// Date Of Products
let productsDB = [
    {
        id: 1,
        img: "images/products/breakfast-2.jpg",
        name: "Lunch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita nemo obcaecati qui perferendis corrupti ex quidem non aliquam veritatis consequuntur?",
        meal: "breakfast",
        price: "12$",
        size: "small",
        quantity: 1,
        isMe: "N",
    },
    {
        id: 2,
        img: "images/products/breakfast-3.jpg",
        name: "breakfast",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita nemo obcaecati qui perferendis corrupti ex quidem non aliquam veritatis consequuntur?",
        meal: "Lunch",
        price: "10$",
        size: "large",
        quantity: 1,
        isMe: "N",
    },
    {
        id: 3,
        img: "images/products/breakfast-4.jpg",
        name: "Dinner",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita nemo obcaecati qui perferendis corrupti ex quidem non aliquam veritatis consequuntur?",
        meal: "Dinner",
        price: "14$",
        size: "medium",
        quantity: 1,
        isMe: "N",
    },
    {
        id: 4,
        img: "images/products/dinner-3.jpg",
        name: "Product",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita nemo obcaecati qui perferendis corrupti ex quidem non aliquam veritatis consequuntur?",
        meal: "breakfast",
        price: "5$",
        size: "small",
        quantity: 1,
        isMe: "N",
    },
];
